<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="USMUMAWANGA11" failures="2" tests="6" name="Test" time="3.62" errors="0" timestamp="2024-02-01T12:40:11 IST">
  <testcase classname="com.demo.tests.PostTests" name="postEmployeeData" time="2.544"/>
  <testcase classname="com.demo.tests.PostTests" name="postEmployeeDataFromExternalFile" time="2.544"/>
  <testcase classname="com.demo.tests.GetTests" name="getEmployees" time="0.074"/>
  <testcase classname="com.demo.tests.PutTests" name="updateEmployeeDetails" time="0.04"/>
  <testcase classname="com.demo.tests.DeleteTests" name="deleteEmployeeDetails" time="0.061">
    <failure type="java.lang.AssertionError" message="
expected: 200
 but was: 404">
      <![CDATA[java.lang.AssertionError: 
expected: 200
 but was: 404
at com.demo.tests.DeleteTests.deleteEmployeeDetails(DeleteTests.java:30)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- deleteEmployeeDetails -->
  <testcase classname="com.demo.tests.GetTests" name="getEmployeeDetails" time="0.972">
    <failure type="java.lang.AssertionError" message="
expected: &amp;quot;Kuhlman&amp;quot;
 but was: &amp;quot;Thiel&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
expected: "Kuhlman"
 but was: "Thiel"
at com.demo.tests.GetTests.getEmployeeDetails(GetTests.java:38)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- getEmployeeDetails -->
</testsuite> <!-- Test -->
